In [1]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])
print(arr2)
print(type(arr2))
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
<class 'numpy.ndarray'>
(2, 5)


In [13]:
arr2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  2],
       [ 4,  6],
       [ 8, 10]])

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
arr3 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [1,3 ,4,5 ,6]])
print(arr3)
print(type(arr3))
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 1  3  4  5  6]]
<class 'numpy.ndarray'>
(3, 5)


In [19]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# element wise
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[ 2  4  6  8 10]
 [ 3  6  9 12 15]]
[[ 0  0  0  0  0]
 [-1 -2 -3 -4 -5]]
[[ 1  4  9 16 25]
 [ 2  8 18 32 50]]
[[1.  1.  1.  1.  1. ]
 [0.5 0.5 0.5 0.5 0.5]]


In [26]:
arr_test = [10, 20, 30, 40, 50]

print(np.sqrt(arr_test))
print(np.exp(arr_test))
print(np.sin(arr_test))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [42]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

# print(arr4[0][0])
# print(len(arr4[0]))
print(arr4[1:2, :2])

[[6 7]]


In [43]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
arr4[1, 2] = 100
arr4

array([[  1,   2,   3,   4,   5],
       [  6,   7, 100,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [47]:
arr4[:2] = 100
arr4

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 11,  12,  13,  14,  15]])

In [50]:
print(np.mean(arr_test))
print(np.var(arr_test))
print(np.median(arr_test))
print(np.std(arr_test))

30.0
200.0
30.0
14.142135623730951


In [57]:
arrr = np.array([1, 3, 4, 5,79, 90, 2])

print(arrr>5)
print(arrr[arrr>5])
print((arrr>5) & (arrr<90))


[False False False False  True  True False]
[79 90]
[False False False False  True False False]
